import React, { useState, useEffect } from 'react';
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import 'bootstrap/dist/css/bootstrap.min.css'
import 'react-bootstrap-table-next/dist/react-bootstrap-table2.min.css'
import 'react-bootstrap-table2-paginator/dist/react-bootstrap-table2-paginator.min.css'
import BootstrapTable from 'react-bootstrap-table-next'
import paginationFactory from "react-bootstrap-table2-paginator"
import {
  Card,
  CardBody,
  CardHeader,
  CardTitle,
  Col,
  Container,
  Row,
  Input,
  InputGroup,
  InputGroupAddon,
  Button,
  Media,
  Badge,
  Navbar,
  NavbarBrand,
  NavbarToggler,
  Collapse,
  Nav,
  NavItem,
  NavLink,
  UncontrolledDropdown,
  DropdownToggle,
  DropdownMenu,
  DropdownItem,
  NavbarText,
} from "reactstrap";


const products = [
    { id: 1, status : "I" , desc: "Create user requirement"},
    { id: 2, status : "C" , desc: "Design database" },
    { id: 3, status : "D" , desc: "Unit testing" },
];

function labelFormatter(cell, row) {

    let color = "secondary";
    let text  = "In Progress";

    switch(cell){
      case "D":
        color = "success";
        text  = "Done";
        break;
      case "C":
        color = "primary";
        text  = "Completed";
        break;
      default:
        break;
    }

    return (
        <span>
            <Badge color={color}>{text}</Badge>
        </span>
    );
}

const columns = [{
  dataField: 'id',
  text: 'Task ID'
}, {
  dataField: 'status',
  text: 'Status',
  formatter: labelFormatter,
}, {
  dataField: 'desc',
  text: 'Description'
}];

const selectRow = {
  mode: "checkbox",
  clickToSelect: false,
  bgColor: "#f8f9fa"
};

const rowStyle = { 
  height: '50px'
};

const colStyle = {
  overflowX: 'auto'
}

export default function Home() {
  const [isOpen, setIsOpen] = useState(false);
  const toggle = () => setIsOpen(!isOpen);

  return (
    <div>
      <Head>
        <title>ToDoNext</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar color="dark" dark expand="md">
        <NavbarBrand href="/">ToDoNext</NavbarBrand>
      </Navbar>

      <div className={styles.container}>
        <main className={styles.main}>
          <Card className="text-muted">
            <CardBody>
              <CardTitle tag="h5">To Do List</CardTitle>
              <BootstrapTable
                keyField="name"
                data      = {products}
                columns   = {columns}
                bootstrap4
                bordered  = {false}
                selectRow = {selectRow}
                rowStyle  = {rowStyle}
                colStyle  = {colStyle}
                headerClasses="header-class"
                pagination={paginationFactory({
                  sizePerPage: 20,
                  sizePerPageList: [10, 20, 50, 100]
                })}
              />
            </CardBody>
          </Card>
        </main>
      </div>
    </div>
  )
}
